#!/bin/sh

unsupported() {
	echo "org.freedesktop.Hal.Device.SystemPowerManagement.NotSupported" >&2
	echo "No shutdown command found" >&2
	exit 1
}

# Use custom shutdown script
if [ -x "/home/myth/scripts/shutdown.pl" ] ; then
	/home/myth/scripts/shutdown.pl
	exit $?
else
	unsupported
fi

# Don't shutdown using the original script; just fall out.
exit 1

###
#Original Ubuntu/hal script content below this line..

#Try for common tools
if [ -x "/sbin/shutdown" ] ; then
	/sbin/shutdown -h now
	exit $?
elif [ -x "/usr/sbin/shutdown" ] ; then
	/usr/sbin/shutdown -h now
	exit $?
else
	unsupported
fi
